<?php
namespace FaganChalabizada\Epoint\Enums;

enum BankResponseCode: string
{
    case UNDEFINED = 'UNDEFINED'; // Confirmed
    case CONFIRMED = '000'; // Confirmed
    case REJECTED_GENERAL = '100'; // Rejected (general, no comment)
    case CARD_EXPIRED = '101'; // Declined, your card has expired
    case SUSPECTED_FRAUD = '102'; // Rejected, suspected fraud
    case CARDHOLDER_CONTACT_ACQUIRER = '103'; // Rejected, cardholder will contact acquirer
    case RESTRICTED_CARD = '104'; // Rejected, Restricted Card
    case CONTACT_ACQUIRER_SECURITY = '105'; // Rejected, Card Receiver will contact Acquirer Security
    case PIN_ATTEMPTS_EXCEEDED = '106'; // Rejected, PIN attempts exceeded
    case CONTACT_CARD_ISSUER = '107'; // Declined, please contact your card issuer
    case REFER_TO_CARD_ISSUER = '108'; // Declined, please refer to card issuer’s special terms
    case INVALID_MERCHANT = '109'; // Rejected, invalid merchant
    case INCORRECT_AMOUNT = '110'; // Rejected, incorrect amount
    case INCORRECT_CARD_NUMBER = '111'; // Rejected, incorrect card number
    case PIN_REQUIRED = '112'; // Rejected, PIN required
    case INAPPROPRIATE_PAYMENT = '113'; // Denied, inappropriate payment
    case NO_ACCOUNT_OF_REQUESTED_TYPE = '114'; // Rejected, no account of the requested type
    case FUNCTION_NOT_SUPPORTED = '115'; // Denied, requested function is not supported
    case INSUFFICIENT_FUNDS = '116'; // Declined, insufficient funds
    case INCORRECT_PIN = '117'; // Rejected, incorrect PIN
    case NO_CARD_DATA = '118'; // Rejected, no card data
    case TRANSACTION_NOT_ALLOWED_BY_CARDHOLDER = '119'; // Rejected, transaction not allowed by cardholder
    case TRANSACTION_NOT_ALLOWED_TO_TERMINAL = '120'; // Rejected, transaction not allowed to terminal
    case WITHDRAWAL_LIMIT_EXCEEDED = '121'; // Declined, withdrawal limit exceeded
    case SAFETY_VIOLATION = '122'; // Rejected, Safety Violation
    case WITHDRAWAL_LIMIT_EXCEEDED_2 = '123'; // Declined, withdrawal limit exceeded
    case VIOLATION_OF_LAW = '124'; // Rejected, violation of the law
    case CARD_NOT_VALID = '125'; // Rejected, card not valid
    case INVALID_PIN_BLOCK = '126'; // Rejected, invalid PIN block
    case PIN_LENGTH_ERROR = '127'; // Rejected, PIN length error
    case PIN_KEY_SYNCHRONIZATION_FAILED = '128'; // Rejected, PIN key synchronization failed
    case SUSPECTED_FAKE_CARD = '129'; // Rejected, suspected fake card
    case REJECTED_AT_CARDHOLDER_REQUEST = '180'; // Rejected, at the request of cardholders
    case PICKUP_GENERAL = '200'; // Pick-up (general, no comment)
    case PICKUP_EXPIRED_CARD = '201'; // Pick-up, expired card
    case PICKUP_SUSPECTED_FRAUD = '202'; // Pick-up, suspected fraud
    case PICKUP_CARD_RECEIVER_CONTACT_ACQUIRER = '203'; // Pick-up, the card receiver will contact the acquirer
    case PICKUP_RESTRICTED_CARD = '204'; // Pick-up, restricted card
    case PICKUP_CONTACT_ACQUIRER_SECURITY = '205'; // Pick-up, the cardholder will contact the acquirer's security department
    case PICKUP_PIN_LIMIT_EXCEEDED = '206'; // Pick-up, PIN limit exceeded
    case PICKUP_SPECIAL_CONDITIONS = '207'; // Pick-up, Special Conditions
    case PICKUP_LOST_CARD = '208'; // Pick-up, lost card
    case PICKUP_STOLEN_CARD = '209'; // Pick-up, stolen card
    case PICKUP_SUSPECTED_FAKE_CARD = '210'; // Pick-up, suspected fake card
    case STATUS_MESSAGE_FILE_ACTION_SUCCESSFUL = '300'; // Status Message File Action Successful
    case STATUS_MESSAGE_FILE_ACTION_NOT_SUPPORTED = '301'; // Status Message File Action Not Supported by Recipient
    case STATUS_MESSAGE_FILE_ENTRY_NOT_FOUND = '302'; // Status Message: Could not find an entry in the file
    case STATUS_MESSAGE_DUPLICATE_RECORD_REPLACED = '303'; // Status Message Duplicate Record, Old Record Replaced
    case STATUS_MESSAGE_FILE_WRITE_FIELD_EDIT_ERROR = '304'; // Status Message File Write Field Edit Error
    case STATUS_MESSAGE_FILE_LOCKED = '305'; // Status Message File Locked
    case STATUS_MESSAGE_FILE_ACTION_FAILED = '306'; // Status Message File Action Failed
    case STATUS_MESSAGE_FILE_DATA_FORMAT_ERROR = '307'; // Status Message File Data Format Error
    case STATUS_MESSAGE_DUPLICATE_RECORD_REJECTED = '308'; // Status Message Duplicate Record, New Record Rejected
    case STATUS_MESSAGE_UNKNOWN_FILE = '309'; // Status Message: Unknown File
    case ACCEPTED_FOR_CANCELLATION = '400'; // Accepted (for cancellation)
    case CONFIRMED_NO_ORIGINAL_MESSAGE_DATA = '499'; // Confirmed, no original message data
    case STATUS_MESSAGE_AGREED_IN_BALANCE_SHEET = '500'; // Status message: agreed, in the balance sheet
    case STATUS_MESSAGE_AGREED_OUT_OF_BALANCE = '501'; // Status message: agreed, out of balance
    case STATUS_MESSAGE_AMOUNT_NOT_AGREED_PROVIDED = '502'; // Status Message: Amount Not Agreed, Amount Provided
    case STATUS_MESSAGE_AMOUNT_NOT_AVAILABLE_FOR_NEGOTIATION = '503'; // Status Message - Amount not available for negotiation
    case STATUS_MESSAGE_NOT_AGREED_AMOUNT_PROVIDED = '504'; // Status message: not agreed, amount provided
    case ACCEPTED_FOR_ADMINISTRATIVE_INFORMATION = '600'; // Accepted (for administrative information)
    case STATUS_MESSAGE_ORIGINAL_TRANSACTION_CANNOT_BE_TRACKED = '601'; // Status Message - Original Transaction Cannot Be Tracked
    case STATUS_MESSAGE_INVALID_TRANSACTION_REFERENCE_NUMBER = '602'; // Status Message Invalid Transaction Reference Number
    case STATUS_MESSAGE_LINK_NUMBER_PANS_INCOMPATIBLE = '603'; // Status Message Link Number/PANs are Incompatible
    case STATUS_MESSAGE_POS_PHOTO_NOT_AVAILABLE = '604'; // Status message: POS photo not available
    case STATUS_MESSAGE_REQUESTED_ITEM_PROVIDED = '605'; // Status Message: Requested Item Provided
    case STATUS_MESSAGE_REQUEST_FAILED_DOCUMENTATION_UNAVAILABLE = '606'; // Status Message Request Failed - Required Documentation Unavailable
    case LIST_READY = '680'; // The list is ready
    case LIST_NOT_READY = '681'; // The list is not ready
    case ACCEPTED_FOR_PAYMENT_COLLECTION = '700'; // Accepted (for payment collection)
    case ACCEPTED_FOR_NETWORK_MANAGEMENT = '800'; // Accepted (for network management)
    case RECOMMENDATION_TAKEN_NO_FINANCIAL_OBLIGATION = '900'; // The recommendation has been taken into account, no financial obligations have been accepted
    case RECOMMENDATION_TAKEN_FINANCIAL_LIABILITY_ACCEPTED = '901'; // Recommendations taken into account, financial liability accepted
    case REJECTION_REASON_INVALID_TRANSACTION = '902'; // Rejection Reason Message: Invalid Transaction
    case STATUS_MESSAGE_REENTER_TRANSACTION = '903'; // Status Message - Re-Enter Transaction
    case REJECTION_REASON_FORMAT_ERROR = '904'; // Rejection Reason Message: Format Error
    case REJECTION_REASON_ACQUIRER_NOT_SUPPORTED_BY_SWITCH = '905'; // Deviation Cause Message Received, Acquirer Not Supported by Switch
    case REJECTION_REASON_PROCESS_REDUCTION = '906'; // Reason for Deviation Report: Process Reduction
    case REJECTION_REASON_CARD_ISSUER_OR_SWITCH_NOT_IN_EFFECT = '907'; // Reason for Rejection Message - Card Issuer or Switch Not in Effect
    case REJECTION_REASON_UNABLE_TO_FIND_DESTINATION = '908'; // Reason for Rejection Message: Unable to find the destination of the routing transaction
    case REJECTION_REASON_SYSTEM_FAILURE = '909'; // Cause of Deviation Report: System Failure
    case REJECTION_REASON_CARD_ISSUER_DISABLED = '910'; // Reason for Rejection Message: Card Issuer Disabled
    case REJECTION_REASON_CARD_ISSUER_EXPIRED = '911'; // Reason for Rejection Message: Card Issuer Expired
    case REJECTION_REASON_ISSUER_UNAVAILABLE = '912'; // Reason for Rejection Message: Issuer Unavailable
    case REJECTION_REASON_DUPLICATE_TRANSMISSION = '913'; // Deviation Cause Message - Duplicate Transmission
    case REJECTION_REASON_FAILED_TO_TRACK_ORIGINAL_TRANSACTION = '914'; // Rejection Reason Message: Failed to track original transaction
    case REJECTION_REASON_FAILED_TO_DISABLE_NEGOTIATION_OR_CHECKPOINT = '915'; // Deviation Cause Message: Failure to Disable Negotiation or Checkpoint
    case REJECTION_REASON_MAC_INCORRECT = '916'; // Reject Cause Message: MAC Incorrect
    case REJECTION_REASON_MAC_KEY_SYNCHRONIZATION_ERROR = '917'; // Reject Cause Message: MAC Key Synchronization Error
    case REJECTION_REASON_NO_BINDING_KEYS_AVAILABLE = '918'; // Reject Cause Message: No binding keys available for use
    case REJECTION_REASON_ENCRYPTION_KEY_SYNCHRONIZATION_ERROR = '919'; // Reject Cause Message: Encryption Key Synchronization Error
    case REJECTION_REASON_SOFTWARE_HARDWARE_SECURITY_ERROR_TRY_AGAIN = '920'; // Cause of Deviation Message: Software/Hardware Security Error - Try Again
    case REJECTION_REASON_SOFTWARE_HARDWARE_SECURITY_ERROR_NO_ACTION = '921'; // Deviation Cause Message: Software/Hardware Security Error - No Action
    case REJECTION_REASON_INCORRECT_MESSAGE_NUMBER_SEQUENCE = '922'; // Rejection Reason Message: Incorrect Message Number Sequence
    case STATUS_MESSAGE_IN_PROCESS_QUERY = '923'; // Status Message In-Process Query
    case REJECTION_REASON_BUSINESS_AGREEMENT_VIOLATION = '950'; // Reason for Rejection Message - Business Agreement Violation
    case CODE_TO_BE_REPLACED_BY_CARD_STATUS_CODE = 'XXX'; // Code to be replaced by card status code or stop list reason code
    case CONFIRMED_OFFLINE_ICC = '0Y1'; // Confirmed, offline ICC
    case CONFIRMED_OFFLINE_ICC_2 = '0Y3'; // Confirmed, offline ICC
    case REJECTED_DUE_TO_ICC_OFFLINE_MODE = '1Q1'; // Rejected due to ICC offline mode
    case REJECTED_DUE_TO_ICC_OFFLINE_MODE_2 = '1Z1'; // Rejected due to ICC offline mode
    case REJECTED_DUE_TO_ICC_OFFLINE_MODE_3 = '1Z3'; // Rejected due to ICC offline mode
}